# Generated by Django 5.1.5 on 2025-01-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registered_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registered_User',
            new_name='Seller',
        ),
    ]
