# Generated by Django 5.1.5 on 2025-01-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='fk2',
        ),
    ]
