# Generated by Django 5.1.5 on 2025-01-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_products_fk2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
