# Generated by Django 5.1.5 on 2025-01-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_admin_deleted_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_deleted_products',
            name='reason',
        ),
    ]
