# Generated by Django 5.1.5 on 2025-01-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_admin_deleted_products_fk3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Deleted_Products',
        ),
    ]
