# Generated by Django 5.1.5 on 2025-01-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_buyers_fk4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyers',
        ),
    ]
