# Generated by Django 5.1.5 on 2025-01-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_buyers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='fk5',
        ),
    ]
