# Generated by Django 5.1.5 on 2025-02-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_razorpay_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpay_transaction',
            name='fk5',
        ),
    ]
