# Generated by Django 5.1.5 on 2025-02-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_delete_razorpay_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpay_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('order_id', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fk5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
            ],
        ),
    ]
