# Generated by Django 5.1.5 on 2025-02-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_razorpay_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odr_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.buyers')),
                ('fk5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.seller')),
            ],
        ),
    ]
