# Generated by Django 5.1.5 on 2025-02-13 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_delete_traction_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.buyers')),
                ('fk5', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.products')),
                ('odr_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.razorpay_transaction')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.seller')),
            ],
        ),
    ]
