# Generated by Django 5.1.5 on 2025-02-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_alter_traction_history_buyer_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traction_history',
            name='buyer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='traction_history',
            name='seller_email',
            field=models.EmailField(max_length=254),
        ),
    ]
