# Generated by Django 5.1.5 on 2025-02-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_traction_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
