# Generated by Django 5.1.5 on 2025-02-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_alter_products_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
