# Generated by Django 5.1.5 on 2025-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_alter_admin_deleted_products_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
