# Generated by Django 5.1.5 on 2025-02-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_alter_seller_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_deleted_seller_account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='admin_deleted_seller_account',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admin_deleted_seller_account',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admin_deleted_seller_account',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
