# Generated by Django 5.1.5 on 2025-02-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_alter_admin_deleted_seller_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
