# Generated by Django 5.1.5 on 2025-02-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_alter_buyers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='fk2',
        ),
        migrations.RemoveField(
            model_name='razorpay_transaction',
            name='fk5',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='fk1',
        ),
        migrations.RemoveField(
            model_name='traction_history',
            name='fkseller',
        ),
        migrations.RemoveField(
            model_name='traction_history',
            name='fkbuyer',
        ),
        migrations.DeleteModel(
            name='Admin_Deleted_Products',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Razorpay_Transaction',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Traction_History',
        ),
    ]
