# Generated by Django 5.1.5 on 2025-01-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_products_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
