# Generated by Django 5.1.5 on 2025-01-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_admin_deleted_products_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_deleted_products',
            name='fk3',
        ),
    ]
