# Generated by Django 5.1.5 on 2025-01-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_admin_deleted_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Deleted_Products',
        ),
    ]
