# Generated by Django 5.1.5 on 2025-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_admin_deleted_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Deleted_Seller_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
