# Generated by Django 5.1.5 on 2025-01-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_buyers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyers',
        ),
    ]
