# Generated by Django 5.1.5 on 2025-02-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_razorpay_transaction_fk5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Razorpay_Transaction',
        ),
    ]
