# Generated by Django 5.1.5 on 2025-02-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Razorpay_Transaction',
        ),
    ]
