# Generated by Django 5.1.5 on 2025-02-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_traction_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traction_history',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.buyers'),
        ),
        migrations.AlterField(
            model_name='traction_history',
            name='fk5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.products'),
        ),
        migrations.AlterField(
            model_name='traction_history',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.seller'),
        ),
    ]
