# Generated by Django 5.1.5 on 2025-02-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_traction_history_buyer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traction_History',
        ),
    ]
