# Generated by Django 5.1.5 on 2025-02-13 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_rename_fk5_traction_history_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fk2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.seller'),
        ),
    ]
