# Generated by Django 5.1.5 on 2025-02-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_alter_products_fk2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traction_History',
        ),
    ]
