# Generated by Django 5.1.5 on 2025-02-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_traction_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traction_history',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='traction_history',
            name='fk2',
        ),
    ]
