# Generated by Django 5.1.5 on 2025-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_traction_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traction_history',
            name='buyer_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='traction_history',
            name='seller_number',
            field=models.IntegerField(),
        ),
    ]
