# Generated by Django 5.1.5 on 2025-02-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_traction_history_buyer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traction_history',
            name='odr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.razorpay_transaction'),
        ),
    ]
