# Generated by Django 5.1.5 on 2025-02-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_traction_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traction_History',
        ),
    ]
