# Generated by Django 5.1.5 on 2025-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_alter_traction_history_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prize',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
