# Generated by Django 5.1.5 on 2025-02-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_alter_products_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_deleted_products',
            name='prize',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
