# Generated by Django 5.1.5 on 2025-02-24 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_remove_products_fk2_remove_razorpay_transaction_fk5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=500)),
                ('prize', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='buyers',
            name='bpic',
            field=models.ImageField(default='default.webp', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Razorpay_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('fk5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('spic', models.ImageField(default='default.webp', upload_to='images/')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('fk1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='fk2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.seller'),
        ),
        migrations.CreateModel(
            name='Admin_Deleted_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=1000)),
                ('prize', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fk3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Traction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=1000)),
                ('prize', models.DecimalField(decimal_places=1, max_digits=10)),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_age', models.IntegerField()),
                ('seller_gender', models.CharField(max_length=10)),
                ('seller_Address', models.CharField(max_length=500)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_number', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_age', models.IntegerField()),
                ('buyer_gender', models.CharField(max_length=10)),
                ('buyer_Address', models.CharField(max_length=500)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('odr_id', models.CharField(max_length=100)),
                ('fkbuyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.buyers')),
                ('fkseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.seller')),
            ],
        ),
    ]
