# Generated by Django 5.1.5 on 2025-02-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_products_buyers_bpic_razorpay_transaction_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='spic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
