# Generated by Django 5.1.5 on 2025-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0079_alter_seller_spic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='bpic',
            field=models.ImageField(default='blank-profile-picture-973460_1280.webp', upload_to='images/'),
        ),
    ]
